Update action.yml

diff --git a/create-org/action.yml b/create-org/action.yml
--- a/create-org/action.yml
+++ b/create-org/action.yml
@@ -65,7 +65,7 @@ runs:
     - name: Create Organization
       shell: bash
       run: |
-        curl -s -H "Authorization: bearer $TOKEN" -X POST -d " \
+        result=$(curl -s -H "Authorization: bearer $TOKEN" -X POST -d " \
           { \
             \"query\": \"mutation { createEnterpriseOrganization ( \
               input: { \
@@ -77,7 +77,16 @@ runs:
               } \
             ) { clientMutationId }}\" \
           } \
-        " https://api.github.com/graphql | jq -e 'has("errors") | not' 
+        " https://api.github.com/graphql)
+        
+        errors=$(echo $result | jq -r '.errors')
+
+        if [ "$errors" != "null" ] && [ "$errors" != "[]" ]; then
+            echo "Errors found: $errors"
+            exit 1
+        else
+            exit 0
+        fi
       env:
           TOKEN: ${{ inputs.admin-pat }}
           ENT_ID: ${{ steps.get-enterprise-id.outputs.ENTERPRISE_ID }}
